CC = gcc
CFLAGS = -Wall -Wextra -Wshadow -g -fsanitize=address -I header_files -I .
LIBS = -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer

SRC = $(wildcard source_files/*.c) main.c
OBJ = game_linux

all: $(OBJ)

$(OBJ): $(SRC)
	$(CC) $(SRC) $(CFLAGS) $(LIBS) -o $(OBJ)

run: $(OBJ)
	LSAN_OPTIONS=suppressions=asan.supp ./$(OBJ)